root.interface.f_remove(root.interface.f_getIndex("scene"))
root.interface.f_remove(root.interface.f_getIndex("cameraMove"))
root.interface.f_remove(root.interface.f_getIndex("minimap"))
root.interface.f_remove(root.interface.f_getIndex("settings"))
root.interface.f_remove(unitPlacingInterface)
root.interface.f_remove(toolsInterface)
